// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicalLotoBackend.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicalLotoBackend.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402041834_RenewedCreate")]
    partial class RenewedCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicalLotoBackend.Domain.Models.GameCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameCards");
                });

            modelBuilder.Entity("MusicalLotoBackend.Domain.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("Playlist")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Rules")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MusicalLotoBackend.Domain.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackgoundImagePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicalLotoBackend.Domain.Models.GameCard", b =>
                {
                    b.HasOne("MusicalLotoBackend.Domain.Models.GameSession", "GameSession")
                        .WithMany("Cards")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("MusicalLotoBackend.Domain.Models.CardCell", "Cells", b1 =>
                        {
                            b1.Property<Guid>("GameCardId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Column");

                            b1.Property<bool>("IsMarked");

                            b1.Property<int>("Row");

                            b1.Property<Guid>("SongId");

                            b1.HasKey("GameCardId", "__synthesizedOrdinal");

                            b1.ToTable("GameCards");

                            b1
                                .ToJson("Cells")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GameCardId");
                        });

                    b.Navigation("Cells");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("MusicalLotoBackend.Domain.Models.GameSession", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
