version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: music_loto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: misha
      POSTGRES_DB: MusicLotoDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./MusicalLotoBackend
      dockerfile: Dockerfile
    container_name: music_loto_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MusicLotoDb;Username=postgres;Password=misha
    volumes:
      - app_wwwroot:/app/wwwroot
    restart: unless-stopped

  frontend:
    build:
      context: ./MusicalLotoFrontend
      dockerfile: Dockerfile
    container_name: music_loto_frontend
    depends_on:
      - api
    ports:
      - "8081:80" # Внутренний контейнер слушает на 80 (nginx), а наружу выдаем на 8081
    restart: unless-stopped

volumes:
  postgres_data:
  app_wwwroot:
